// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pozblfzhjqlsxkakhowp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvemJsZnpoanFsc3hrYWtob3dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMDM0MDUsImV4cCI6MjA1NTY3OTQwNX0.qICEbtyj5hsnu489FuQFiwfFgAJbQ0zmul4sQX5ODbM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Detect mobile for better client options
const isMobileDevice = typeof navigator !== 'undefined' && 
  /iPhone|iPad|iPod|Android/i.test(navigator.userAgent);

// Configure supabase client with mobile-specific options
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      storageKey: 'zerovacancy-auth',
      // Mobile optimizations
      flowType: isMobileDevice ? 'implicit' : 'pkce',
      // Increased timeout for mobile networks
      debug: isMobileDevice
    },
    // Better network resilience
    global: {
      fetch: (...args) => {
        return fetch(...args).catch(err => {
          console.error('Supabase fetch error:', err);
          throw err;
        });
      }
    }
  }
);