name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint
      
      - name: Type check
        run: npm run typecheck
      
      - name: Run tests
        run: npm run test
        
      - name: Generate coverage report
        run: npm run test:coverage
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          flags: unittests
          fail_ci_if_error: true
          verbose: true

  cls-lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: CLS Linting
        run: node scripts/lint-cls-problems.js --strict
        continue-on-error: true
      
      - name: Upload CLS Lint Report
        uses: actions/upload-artifact@v3
        with:
          name: cls-lint-report
          path: cls-reports/cls-lint-*.txt
          retention-days: 14
  
  # This job runs the existing CLS testing workflow
  # If more detailed CLS tests are needed, they'll run in the cls-testing.yml workflow
  cls-quick-check:
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
      
      - name: Start local server
        run: npx serve dist -p 3000 &
      
      - name: Wait for server
        run: sleep 5
      
      - name: Run CLS quick check
        run: node scripts/automated-cls-testing.js --url=http://localhost:3000 --threshold=0.1 --ci
        continue-on-error: true
      
      - name: Upload CLS test results
        uses: actions/upload-artifact@v3
        with:
          name: cls-test-results
          path: cls-reports/
          retention-days: 14